apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

commonLabels:
  # required to match serviceMonitorSelector
  k8s-app: node-update

resources:
- ./kured.yaml
- ./yumsecupdater.yaml
