---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-update

commonLabels:
  app: yumsecupdater

images:
- name: yumsecupdater
  newName: myregistry.com/yumsecupdater
  newTag: latest

resources:
- daemonset.yaml
- serviceaccount.yaml
- service.yaml
