---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-update

commonLabels:
  app: kured

images:
- name: kured
  newName: myregistry.com/kured
  newTag: 1.7.0

resources:
- clusterrolebinding.yaml
- clusterrole.yaml
- daemonset.yaml
- rolebinding.yaml
- role.yaml
- serviceaccount.yaml
- service.yaml
