apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-monitoring

commonLabels:
  app: grafana-nodes-updates

configMapGenerator:
- name: grafana-dashboard-nodes-updates
  files:
    - ./dashboard/grafana-dashboard-nodes-updates.json

resources:
- deployment.yaml
- service.yaml
- route.yaml
