{
 "title": "Node security updates",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(yumsecupdater_packages_with_update_total,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes with updates",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(yumsecupdater_packages_with_update_total > 0) by (instance))"
    }
   ]
  },
  {
   "title": "Up-to-date nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(yumsecupdater_packages_with_update_total == 0) / count(yumsecupdater_packages_with_update_total) * 100"
    }
   ]
  },
  {
   "title": "Nodes with reboot required due to security patches",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kured_reboot_required" }
   ]
  },
  {
   "title": "Nodes with reboot required",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kured_reboot_required == 1) by (instance))"
    }
   ]
  },
  {
   "title": "Nodes properly rebooted",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(kured_reboot_required == 0) by (instance)) / count(count(kured_reboot_required) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "time() - (max(node_boot_time_seconds) by (instance))"
    }
   ]
  },
  {
   "title": "Nodes with uptime above 90 days",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((time() - (max(node_boot_time_seconds) by (instance))) > (90*24*3600))"
    }
   ]
  },
  {
   "title": "Nodes with uptime below 90 days",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "count((time() - (max(node_boot_time_seconds) by (instance))) < (90*24*3600)) / count(count(node_boot_time_seconds) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Available updates per node",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "yumsecupdater_package_with_update{node=~\"$node\"}"
    }
   ]
  }
 ]
}